@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Mar 14 02:03:35 +0300 2024
REM SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
REM
REM IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim TOP_MODULE_SIM_behav -key {Behavioral:sim_1:Functional:TOP_MODULE_SIM} -tclbatch TOP_MODULE_SIM.tcl -view C:/Users/Emorh/OneDrive/Desktop/102_reopen/102_reopen_git/102_reopen/102_reopen_vhdl/TOP_MODULE_SIM_behav.wcfg -log simulate.log"
call xsim  TOP_MODULE_SIM_behav -key {Behavioral:sim_1:Functional:TOP_MODULE_SIM} -tclbatch TOP_MODULE_SIM.tcl -view C:/Users/Emorh/OneDrive/Desktop/102_reopen/102_reopen_git/102_reopen/102_reopen_vhdl/TOP_MODULE_SIM_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
